Bug fixes and prefixes
Fixing bugs and making docker command prefix handling more generic

diff --git a/operations/bashrc b/operations/bashrc
--- a/operations/bashrc
+++ b/operations/bashrc
@@ -1,17 +1,5 @@
-# .bashrc
-
-# Source global definitions
-if [ -f /etc/bashrc ]; then
-	. /etc/bashrc
-fi
-
-# Uncomment the following line if you don't like systemctl's auto-paging feature:
-# export SYSTEMD_PAGER=
-
-# User specific aliases and functions
-
 #START DAP convenience aliases
-function prompt_confirm() {
+function prompt_confirm {
   while true; do
     read -r -n 1 -p "${1:-Continue?} [y/n]: " REPLY
     case $REPLY in
@@ -21,16 +9,25 @@ function prompt_confirm() {
     esac
   done
 }
-function _container_name() {
-	prefix="$(_docker_prefix_cmd)"
-	$prefix docker ps --format "{{.ID}}\{{.Image}}\{{.Names}}" | grep conjur-appliance | awk -F\\ '{print $NF}'
+function _docker_prefix_cmd {
+    if [ "$(command -v docker)" = "" ]; then
+        echo "Could not find docker! Is it installed?"
+        exit 1
+    fi
+    if [ "$(docker ps >/dev/null 2>&1)" = "1" ]; then
+         echo "sudo"
+         return
+    fi
+    echo ""
 }
-function _docker_prefix_cmd() {
-	if "$(docker ps >/dev/null 2>&1)" == "1"; then
-	     echo "sudo"
-	fi
+function _docker {
+    prefix="$(_docker_prefix_cmd)"
+    $prefix docker $@
 }
-function _dap_config_master() {
+function _container_name {
+    _docker ps --format "{{.ID}}\{{.Image}}\{{.Names}}" | grep conjur-appliance | awk -F\\ '{print $NF}'
+}
+function _dap_config_master {
 	echo "==== "
 	echo "NOTICE: This shortcut may not reflect current guidance for configuring a master."
 	echo "        Please refer to the documentation to ensure the command is valid for "
@@ -45,7 +42,7 @@ function _dap_config_master() {
 			prompt_confirm "Password did not meet complexity requirements. Try again?" || return
 			continue
 		fi
-		if [ "$admin1" == "$confirm1" ]; then
+		if [ "$admin1" = "$confirm1" ]; then
 			break
 		else
 			prompt_confirm "Password did not match. Try again?" || return
@@ -59,7 +56,7 @@ function _dap_config_master() {
 	done
 	host_t="$(echo $mhost | awk -F. '{print $1}')"
 	fqdn="$(echo $mhost | sed "s/$host_t//g" | sed "s/^.//g")"
-	if [ "$fqdn" == "" ]; then fqdn="example.com";fi
+	if [ "$fqdn" = "" ]; then fqdn="example.com";fi
 	while true; do
 		echo "Master alternative name FQDNs --"
 		echo "Single Master/3rd Party Certificates: leave this empty"
@@ -84,80 +81,88 @@ function _dap_config_master() {
 	fi
 	echo "  $orgname"
 }
-function _dap_config_standby() {
-	local seed=$1
-	local test=$2
-	test -f "$seed" || { echo "Usage: dap_config_standby <path/to/seed_file.tar>"; return; }
-	prefix="$(_docker_prefix_cmd)"
-	container_name="$(_container_name)"
+function _dap_config_standby {
+	local t_echo=$1
+	local seed=$2
+    	if [ "$t_echo" != "echo" ]; then seed=$1;t_echo="";fi
+	if [ ! -f "$seed" ];then echo "Usage: dap_config_standby [echo] <path/to/seed_file.tar>"; return; fi
 	filename="$(echo "$seed" | awk -F/ '{print $NF}')"
-	$test $prefix docker cp $seed $container_name:/tmp/
-	$test $prefix docker exec $container_name unpack seed /tmp/$filename
-	$test $prefix docker exec $container_name evoke configure standby
-}
-function _dap_config_follower() {
-	local seed=$1
-	local test=$2
-	test -f "$seed" || { echo "Usage: dap_config_follower <path/to/seed_file.tar>"; return; }
-	filename="$(echo "$seed" | awk -F/ '{print $NF}')"
-	prefix="$(_docker_prefix_cmd)"
 	container_name="$(_container_name)"
-	$test $prefix docker cp $seed $container_name:/tmp/
-	$test $prefix docker exec $container_name unpack seed /tmp/$filename
-	$test $prefix docker exec $container_name evoke configure follower
+    	prefix="$(_docker_prefix_cmd)"
+	if [ ! -z "$t_echo" ];then echo " -- Echoing commands. To run these commands, remove the 'echo' from the dap_config_standby command.";fi
+	$t_echo $prefix docker cp $seed $container_name:/tmp/
+	$t_echo $prefix docker exec $container_name unpack seed /tmp/$filename
+	$t_echo $prefix docker exec $container_name evoke configure standby
 }
-function _daphealth() {
+function _dap_config_follower {
+	local t_echo=$1
+	local seed=$2
+    	if [ "$t_echo" != "echo" ]; then seed=$1;t_echo="";fi
+	if [ ! -f "$seed" ];then echo "Usage: dap_config_follower [echo] <path/to/seed_file.tar>"; return; fi
+	filename="$(echo "$seed" | awk -F/ '{print $NF}')"
+	container_name="$(_container_name)"
+    	prefix="$(_docker_prefix_cmd)"
+	if [ ! -z "$t_echo" ];then echo " -- Echoing commands. To run these, remove the 'echo' from the dap_config_follower command.";fi
+	$t_echo $prefix docker cp $seed $container_name:/tmp/
+	$t_echo $prefix docker exec $container_name unpack seed /tmp/$filename
+	$t_echo $prefix docker exec $container_name evoke configure follower
+}
+function _daphealth {
 	local sflag="" # Suppress curl stats if piping output to another command like jq
 	local hname="$(echo "$@" | sed 's/-s//g' | sed 's/ //g')"
-        if [ "$1" == "-s" ];then sflag="-s"; fi
+        if [ "$1" = "-s" ];then sflag="-s"; fi
 	if test -z "$hname"; then hname="localhost"; fi
 	url="https://$hname/health"
 	curl $sflag -k "$url"
 }
-function _dapinfo() {
+function _dapinfo {
 	local sflag="" # Suppress curl stats if piping output to another command like jq
 	local hname="$(echo "$@" | sed 's/-s//g' | sed 's/ //g')"
-        if [ "$1" == "-s" ];then sflag="-s"; fi
+        if [ "$1" = "-s" ];then sflag="-s"; fi
 	if test -z "$hname"; then hname="localhost"; fi
 	url="https://$hname/info"
 	curl $sflag -k "$url"
 }
-function _dapaccount() {
+function _dapaccount {
 	_dapinfo -s "$@" | jq -r '.configuration.conjur.account'
 }
-function _daprole() {
+function _daprole {
 	_dapinfo -s "$@" | jq -r '.configuration.conjur.role'
 }
-function _dapauth_configured() {
+function _dapauth_configured {
 	_dapinfo -s "$@" | jq -r '.authenticators.configured | join(",")'
 }
-function _dapauth_enabled() {
+function _dapauth_enabled {
 	_dapinfo -s "$@" | jq -r '.authenticators.enabled | join(",")'
 }
-function _server_certificate() {
+function _server_certificate {
 	local hname=$1
 	local port=$2
 	test -z "$hname" && hname="localhost"
 	test -z "$port" && port="443"
 	echo -n | openssl s_client -connect "$hname:$port" -servername "$hname" | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
 }
-function _dap_evoke() {
+function _dap_evoke {
 	local it=""
 	local eargs="$(echo "$@" | sed 's/^-it//g')"
-	prefix="$(_docker_prefix_cmd)"
 	container_name="$(_container_name)"
-	if [ "$1" == "-it" ];then it="-it";fi
-	$prefix docker exec $it $container_name evoke $eargs
+	if [ "$1" = "-it" ];then it="-it";fi
+	_docker exec $it $container_name evoke $eargs
 }
-function _dap_exec() {
+function _dap_exec {
 	local it=""
 	local eargs="$(echo "$@" | sed 's/^-it//g')"
-	prefix="$(_docker_prefix_cmd)"
 	container_name="$(_container_name)"
-	if [ "$1" == "-it" ];then it="-it";fi
-	$prefix docker exec $it $container_name $eargs
+	if [ "$1" = "-it" ];then it="-it";fi
+	_docker exec $it $container_name $eargs
 }
-function _dap_display_aliases() {
+function _dap_display_aliases {
+    # BSD versus GNU column command flags hack
+    column_flags="-s ',' -t"
+    echo "a,b" | column -s ',' -t -o'   - ' -N "Info Commands,Description" -W Description >/dev/null 2>&1
+    if [ "$?" = "0" ]; then
+        column_flags="$column_flags -o'   - ' -N \"Info Commands,Description\" -W Description"
+    fi
 	echo "=============== DAP AMI Commands ================="
 	echo """
 	-------------------,-------------------
@@ -176,10 +181,10 @@ function _dap_display_aliases() {
 	dapbash,Start an interactive bash shell in the DAP container.
 	-------------------,-------------------
 	dap_config_master,Prompts for input required to configure a master. Outputs the command for copy/paste.
-	dap_config_standby  [echo],Configure a standby. ex: dap_config_standby ~/standby-seed.tar
-	dap_config_follower [echo],Configure a follower. ex: dap_config_follower ~/follower-seed.tar
+	dap_config_standby  [echo],Configure a standby. ex: dap_config_standby [echo] ~/standby-seed.tar
+	dap_config_follower [echo],Configure a follower. ex: dap_config_follower [echo] ~/follower-seed.tar
 	**NOTE**,Config standby and follower aliases execute the commands unless the echo argument is provided.
-	""" | sed 's/\t//g' | column -s ',' -t -o'   - ' -N "Info Commands,Description" -W Description
+	""" | sed "s/$(echo a | tr 'a' '\t')//g" | column $column_fags
 	echo "=============== DAP AMI Commands ================="
 	echo -e "\nEdit .bashrc to stop displaying this list."
 }
